### ISSUE TITLE
switch short circuiting does not work in python

### ISSUE THREAD

**Issue by bhearsum** [json-e/json-e#544]
For example:
```
Python 3.11.6 (main, Nov 27 2023, 13:45:10) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsone
>>> yaml = """
... foo:
...   $switch:
...     'thing == "thing1"': ${vars.thing1}
...     'thing == "thing2"': ${vars.thing2}
... """
>>> import pprint
>>> pprint.pprint(jsone.render(yaml, {"thing": "thing1", "vars": {"thing1": "THING1", "thing2": "THING2"}}))
('\n'
 'foo:\n'
 '  $switch:\n'
 '    \'thing == "thing1"\': THING1\n'
 '    \'thing == "thing2"\': THING2\n')
>>> pprint.pprint(jsone.render(yaml, {"thing": "thing1", "vars": {"thing1": "THING1"}}))
Traceback (most recent call last):
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/interpreter.py", line 117, in visit_BinOp
    return left[right]
           ~~~~^^^^^^^
KeyError: 'thing2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/__init__.py", line 21, in render
    rv = renderValue(template, full_context)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/render.py", line 531, in renderValue
    return interpolate(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/render.py", line 118, in interpolate
    parsed, offset = parse_until_terminator(string, context, "}")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/render.py", line 100, in parse_until_terminator
    result = interp.interpret(tree)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/interpreter.py", line 200, in interpret
    return self.visit(tree)
           ^^^^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/interpreter.py", line 18, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/jsone/lib/python3.11/site-packages/jsone/interpreter.py", line 119, in visit_BinOp
    raise InterpreterError('object has no property "{}"'.format(right))
jsone.shared.InterpreterError: InterpreterError: object has no property "thing2"
```

This same thing works in the Playground at the very least:
![image](https://github.com/user-attachments/assets/4b7d865a-b65c-490d-9733-7ed578fb4e2d)

(I haven't tested other languages.)

**Comment by bhearsum** [comment]
Okay, so this is actually easily worked around with `eval`:
```
import jsone
import pprint

yaml = """
foo:
  $switch:
    'thing == "thing1"': {$eval: {vars.thing1}}
    'thing == "thing2"': {$eval: {vars.thing2}}
"""

pprint.pprint(jsone.render(yaml, {"thing": "thing1", "vars": {"thing1": "THING1", "thing2": "THING2"}}))
pprint.pprint(jsone.render(yaml, {"thing": "thing1", "vars": {"thing1": "THING1"}}))

('\n'
 'foo:\n'
 '  $switch:\n'
 '    \'thing == "thing1"\': {$eval: {vars.thing1}}\n'
 '    \'thing == "thing2"\': {$eval: {vars.thing2}}\n')
('\n'
 'foo:\n'
 '  $switch:\n'
 '    \'thing == "thing1"\': {$eval: {vars.thing1}}\n'
 '    \'thing == "thing2"\': {$eval: {vars.thing2}}\n')

```

...but it still represents a behaviour difference.

**Comment by bhearsum** [comment]
Oh...in a more advanced case, the keys of the `switch` statement may note be getting processed in the order they appear, which is of course dependent on the yaml parser...

**Comment by djmitche** [comment]
I think this is the same issue as #545 -- you're rendering a string, not a data structure.
